apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-ms
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-ms
  template:
    metadata:
      labels:
        app: nodejs-ms
    spec:
      containers:
        - name: nodejs-ms
          image: nodejs-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: "/placeholder/health"
            initialDelaySeconds: 15
          startupProbe:
            httpGet:
              port: 8080
              path: "/placeholder/health"
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              port: 8080
              path: "/placeholder/health"
            initialDelaySeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-ms
  namespace: default
spec:
  selector:
    app: nodejs-ms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-ms
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-ms
  minReplicas: 3
  maxReplicas: 9
  targetCPUUtilizationPercentage: 70
